WebStore/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebStore.Infrastructure.Interface;
using WebStore.Models;

namespace WebStore.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IOrdersService _ordersService;

        public ProfileController(IOrdersService ordersService)
        {
            _ordersService = ordersService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Orders()
        {
            var orders = _ordersService.GetUserOrders(User.Identity.Name);
            var orderModels=new List<UserOrderViewModel>(orders.Count());
            foreach (var order in orders)
            {
                orderModels.Add(new UserOrderViewModel()
                {
                    Id = order.Id,
                    Name = order.Name,
                    Address = order.Address,
                    Phone = order.Phone,
                    TotalSum = order.OrderItems.Sum(o => o.Price * o.Quantity)
                });
            }

            return View(orderModels);
        }

    }
}

WebStore/Views/Shared/Components/LoginLogout/Default.cshtml
@if (User.Identity.IsAuthenticated)
{
    <span>
        Здравствуйте, <a asp-action="Index"
                         asp-controller="Profile">@User.Identity.Name</a>
                    </span>
                    <form method="post" asp-controller="Account" asp-action="Logout"
                          asp-antiforgery="true">
                        <input type="submit" value="Выход" class="btn btn-default" />
                    </form>
                }
                else
                {
                    <div class="btn-group pull-right">
                        <a asp-action="Login" asp-controller="Account" class="btn
btn-default">Вход</a>
                        <a asp-action="Register" asp-controller="Account" class="btn
btn-default">Регистрация</a>
                    </div>
                }