WebStore/Models/SectionViewModel.cs
using System.Collections.Generic;
using WebStore.DomainNew.Entities.Base.Interfaces;

namespace WebStore.Models
{
    public class SectionViewModel:INamedEntity, IOrderedEntity
    {
        public SectionViewModel()
        {
            ChildSections=new List<SectionViewModel>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int Order { get; set; }

        public List<SectionViewModel> ChildSections { get; set; }
        public SectionViewModel ParentSection { get; set; }
    }
}

WebStore/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebStore.DomainNew.Filters;
using WebStore.Infrastructure.Interface;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IProductData _productService;

        public CatalogController(IProductData productService)
        {
            _productService = productService;
        }


        public IActionResult Shop(int? sectionId, int? brandId)
        {
            var products = _productService.GetProducts(new ProductFilter
            {
                BrandId = brandId,
                SectionId = sectionId
            });
            var model = new CatalogViewModel()
            {
                BrandId = brandId,
                SectionId = sectionId,
                Products = products.Select(p => new ProductViewModel()
                {
                    Id = p.Id,
                    ImageUrl = p.ImageUrl,
                    Name = p.Name,
                    Order = p.Order,
                    Price = p.Price,
                    BrandName = p.Brand?.Name ?? string.Empty
                }).OrderBy(p => p.Order).ToList()
            };
            return View(model);
        }

        public IActionResult ProductDetails(int id)
        {
            var product = _productService.GetProductById(id);
            if (product == null)
                return NotFound();
            return View(new ProductViewModel
            {
                Id = product.Id,
                ImageUrl = product.ImageUrl,
                Name = product.Name,
                Order = product.Order,
                Price = product.Price,
                BrandName = product.Brand?.Name ?? string.Empty
            });
        }
    }
}

WebStore/Views/Shared/Components/Sections/Default.cshtml
@model IEnumerable<WebStore.Models.SectionViewModel>
<h2> Категории </h2>
<div class="panel-group category-products" id="accordian">
    <!--category-products-->
    @foreach (var parentSection in Model)
    {
        if (parentSection.ChildSections.Count > 0)
        {
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordian"
                           href="#@parentSection.Name.ToLower()">
                            <span class="badge pull-right">
                                <i class="fa fa-plus"></i>
                            </span>
                            @parentSection.Name
                        </a>
                    </h4>
                </div>
                <div id="@parentSection.Name.ToLower()" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul>
                            @foreach (var childSection in
                              parentSection.ChildSections)
                            {
                                <li>
                                    <a asp-controller="Catalog"
                                       asp-action="Shop" asp-route-sectionId="@childSection.Id">
                                        @childSection.Name
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a asp-controller="Catalog"
                           asp-action="Shop"
                           asp-route-sectionId="@parentSection.Id">@parentSection.Name</a>
                    </h4>
                </div>
            </div>
        }
    }
</div> <!--/category-products-->